
// product action types
export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE';

export const FETCH_MEN_CLOTHES_REQUEST = 'FETCH_MEN_CLOTHES_REQUEST';
export const FETCH_MEN_CLOTHES_SUCCESS = 'FETCH_MEN_CLOTHES_SUCCESS';
export const FETCH_MEN_CLOTHES_FAILURE = 'FETCH_MEN_CLOTHES_FAILURE';

export const FETCH_WOMEN_CLOTHES_REQUEST = 'FETCH_WOMEN_CLOTHES_REQUEST';
export const FETCH_WOMEN_CLOTHES_SUCCESS = 'FETCH_WOMEN_CLOTHES_SUCCESS';
export const FETCH_WOMEN_CLOTHES_FAILURE = 'FETCH_WOMEN_CLOTHES_FAILURE';

export const FETCH_ELECTRONICS_REQUEST = 'FETCH_ELECTRONICS_REQUEST';
export const FETCH_ELECTRONICS_SUCCESS = 'FETCH_ELECTRONICS_SUCCESS';
export const FETCH_ELECTRONICS_FAILURE = 'FETCH_ELECTRONICS_FAILURE';

export const FETCH_JEWELERY_REQUEST = 'FETCH_JEWELERY_REQUEST';
export const FETCH_JEWELERY_SUCCESS = 'FETCH_JEWELERY_SUCCESS';
export const FETCH_JEWELERY_FAILURE = 'FETCH_JEWELERY_FAILURE';

export const FETCH_PRODUCT_BY_ID_REQUEST = 'FETCH_PRODUCT_BY_ID_REQUEST';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';

// user action types
export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILURE = 'USER_SIGNIN_FAILURE';

export const SET_USER_MONEY = 'SET_USER_MONEY';
export const SET_USER_PURCHASED_ITEMS = 'SET_USER_PURCHASED_ITEMS';

// shopping-cart action types
export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART';
export const PRODUCT_REMOVED_FROM_CART = 'PRODUCT_REMOVED_FROM_CART';
export const PRODUCT_TYPE_REMOVED_FROM_CART = 'PRODUCT_TYPE_REMOVED_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

