
export const FETCH_ALL_PRODUCTS_REQUEST = 'FETCH_ALL_PRODUCTS_REQUEST';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_ALL_PRODUCTS_SUCCESS';
export const FETCH_ALL_PRODUCTS_FAILURE = 'FETCH_ALL_PRODUCTS_FAILURE';

export const FETCH_MEN_CLOTHES_REQUEST = 'FETCH_MEN_CLOTHES_REQUEST';
export const FETCH_MEN_CLOTHES_SUCCESS = 'FETCH_MEN_CLOTHES_SUCCESS';
export const FETCH_MEN_CLOTHES_FAILURE = 'FETCH_MEN_CLOTHES_FAILURE';

export const FETCH_WOMEN_CLOTHES_REQUEST = 'FETCH_WOMEN_CLOTHES_REQUEST';
export const FETCH_WOMEN_CLOTHES_SUCCESS = 'FETCH_WOMEN_CLOTHES_SUCCESS';
export const FETCH_WOMEN_CLOTHES_FAILURE = 'FETCH_WOMEN_CLOTHES_FAILURE';

export const FETCH_ELECTRONICS_REQUEST = 'FETCH_ELECTRONICS_REQUEST';
export const FETCH_ELECTRONICS_SUCCESS = 'FETCH_ELECTRONICS_SUCCESS';
export const FETCH_ELECTRONICS_FAILURE = 'FETCH_ELECTRONICS_FAILURE';

export const FETCH_JEWELERY_REQUEST = 'FETCH_JEWELERY_REQUEST';
export const FETCH_JEWELERY_SUCCESS = 'FETCH_JEWELERY_SUCCESS';
export const FETCH_JEWELERY_FAILURE = 'FETCH_JEWELERY_FAILURE';

export const FETCH_PRODUCT_BY_ID_REQUEST = 'FETCH_PRODUCT_BY_ID_REQUEST';
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS';
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE';


